[ValidateApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[ValidateApp | INFO] Validating '/home/dhruvsus/ps5'
[ValidateApp | ERROR] Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/apps/validateapp.py", line 68, in start
        validator.validate_and_print(filename)
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/validator.py", line 257, in validate_and_print
        results = self.validate(filename)
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/validator.py", line 228, in validate
        nb = self._preprocess(basename)
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/validator.py", line 216, in _preprocess
        nb = read_nb(filename, as_version=current_nbformat)
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/nbgraderformat/v1.py", line 124, in read_v1
        nb = _read(source, as_version, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
        with io.open(fp, encoding='utf-8') as f:
    IsADirectoryError: [Errno 21] Is a directory: '.'
    
[ValidateApp | ERROR] nbgrader encountered a fatal error while trying to validate '.'
[ValidateApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[ValidateApp | INFO] Validating '/home/dhruvsus/ps5/Checkerboard.ipynb'
[ValidateApp | INFO] Executing notebook with kernel: python3
[ValidateApp | INFO] Validating '/home/dhruvsus/ps5/data'
[ValidateApp | ERROR] Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/apps/validateapp.py", line 68, in start
        validator.validate_and_print(filename)
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/validator.py", line 257, in validate_and_print
        results = self.validate(filename)
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/validator.py", line 228, in validate
        nb = self._preprocess(basename)
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/validator.py", line 216, in _preprocess
        nb = read_nb(filename, as_version=current_nbformat)
      File "/opt/conda/lib/python3.6/site-packages/nbgrader/nbgraderformat/v1.py", line 124, in read_v1
        nb = _read(source, as_version, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
        with io.open(fp, encoding='utf-8') as f:
    IsADirectoryError: [Errno 21] Is a directory: 'data'
    
[ValidateApp | ERROR] nbgrader encountered a fatal error while trying to validate 'data'
[ValidateApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[ValidateApp | INFO] Validating '/home/dhruvsus/ps5/Checkerboard.ipynb'
[ValidateApp | INFO] Executing notebook with kernel: python3
[ValidateApp | INFO] Validating '/home/dhruvsus/ps5/FlightsEDA.ipynb'
[ValidateApp | INFO] Executing notebook with kernel: python3
[ValidateApp | INFO] Validating '/home/dhruvsus/ps5/StudentAlcoholEDA.ipynb'
[ValidateApp | INFO] Executing notebook with kernel: python3
[ValidateApp | INFO] Validating '/home/dhruvsus/ps5/Tokenization.ipynb'
[ValidateApp | INFO] Executing notebook with kernel: python3
[ValidateApp | ERROR] Timeout waiting for execute reply (30s).
[ValidateApp | ERROR] Interrupting kernel
[SubmitApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[SubmitApp | INFO] Source: /home/dhruvsus/ps5
[SubmitApp | INFO] Destination: /srv/nbgrader/exchange/data301/inbound/dhruvsus+ps5+2018-01-30 16:24:53.549299 UTC
[SubmitApp | WARNING] Possible missing notebooks and/or extra notebooks submitted for assignment ps5:
    Expected:
    	Checkerboard.ipynb: FOUND
    	FlightsEDA.ipynb: FOUND
    	StudentAlcoholEDA.ipynb: FOUND
    	Tokenization.ipynb: FOUND
    Submitted:
    	.ipynb_checkpoints/Checkerboard-checkpoint.ipynb: EXTRA
    	.ipynb_checkpoints/FlightsEDA-checkpoint.ipynb: EXTRA
    	.ipynb_checkpoints/StudentAlcoholEDA-checkpoint.ipynb: EXTRA
    	.ipynb_checkpoints/Tokenization-checkpoint.ipynb: EXTRA
    	Checkerboard.ipynb: OK
    	FlightsEDA.ipynb: OK
    	StudentAlcoholEDA.ipynb: OK
    	Tokenization.ipynb: OK
[SubmitApp | INFO] Submitted as: data301 ps5 2018-01-30 16:24:53.549299 UTC
[ValidateApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[ValidateApp | INFO] Validating '/home/dhruvsus/ps5/Checkerboard.ipynb'
[ValidateApp | INFO] Executing notebook with kernel: python3
[ValidateApp | INFO] Validating '/home/dhruvsus/ps5/FlightsEDA.ipynb'
[ValidateApp | INFO] Executing notebook with kernel: python3
[ValidateApp | INFO] Validating '/home/dhruvsus/ps5/StudentAlcoholEDA.ipynb'
[ValidateApp | INFO] Executing notebook with kernel: python3
[ValidateApp | INFO] Validating '/home/dhruvsus/ps5/Tokenization.ipynb'
[ValidateApp | INFO] Executing notebook with kernel: python3
[ValidateApp | ERROR] Timeout waiting for execute reply (30s).
[ValidateApp | ERROR] Interrupting kernel
[SubmitApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[SubmitApp | INFO] Source: /home/dhruvsus/ps5
[SubmitApp | INFO] Destination: /srv/nbgrader/exchange/data301/inbound/dhruvsus+ps5+2018-01-30 16:27:29.976876 UTC
[SubmitApp | WARNING] Possible missing notebooks and/or extra notebooks submitted for assignment ps5:
    Expected:
    	Checkerboard.ipynb: FOUND
    	FlightsEDA.ipynb: FOUND
    	StudentAlcoholEDA.ipynb: FOUND
    	Tokenization.ipynb: FOUND
    Submitted:
    	.ipynb_checkpoints/Checkerboard-checkpoint.ipynb: EXTRA
    	.ipynb_checkpoints/FlightsEDA-checkpoint.ipynb: EXTRA
    	.ipynb_checkpoints/StudentAlcoholEDA-checkpoint.ipynb: EXTRA
    	.ipynb_checkpoints/Tokenization-checkpoint.ipynb: EXTRA
    	Checkerboard.ipynb: OK
    	FlightsEDA.ipynb: OK
    	StudentAlcoholEDA.ipynb: OK
    	Tokenization.ipynb: OK
